# MVC CONFIGURATION:

server:
  port: 8083
  use-forward-headers: true
  servlet:
    context-path: /
    session:
      timeout: 1d

# PERSISTENCE OPTIONS:

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
