# MVC CONFIGURATION - GENERAL:

server:
  port: 8083
  use-forward-headers: true
  servlet:
    context-path: /
    session:
      timeout: 1d

# PERSISTENCE OPTIONS - GENERAL:

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always

# NHS REST API CONNECTION PROPERTIES - GENERAL:

nhs:
  rest:
    doctors-uri: "/doctors"
    credentials: "MEDICOM:P@ssW0rd!"
    patients-uri: "/patients"
