# PERSISTENCE - REMOTE MYSQL DATABASE:

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:xx.xxx.xx.xxx}/medicom
    username: "medicom"
    password: "@Medicom@3"

# REST API CONNECTION - REMOTE:

nhs:
  rest:
    server-url: "https://nhsbackend.myserverapps.com"
