package ro.iteahome.medicom.model.reference;

public enum UserRole {

    ADMIN,
    // CAN EDIT MEDICOM USERS.
    // CAN EDIT MEDICOM INSTITUTIONS.
    // CANNOT EDIT MEDICOM CALENDARS. A NEW CALENDAR SHOULD BE AUTOMATICALLY CREATED AND ASSIGNED TO NEW INSTITUTIONS UPON THEIR REGISTRATION INTO THE MEDICOM SYSTEM.
    // CANNOT ACCESS NHS DATABASE.
    // IS NOT A MEDICAL PROFESSIONAL, HAS NO LICENSE NUMBER.

    DOCTOR,
    // CANNOT VIEW/EDIT MEDICOM USERS, EXCEPT THEIR OWN.
    // CANNOT VIEW/EDIT MEDICOM INSTITUTIONS, EXCEPT VIEWING THEIR OWN.
    // CAN ONLY EDIT THEIR OWN INSTITUTION'S MEDICOM CALENDAR.
    // CAN ACCESS NHS DATABASE:
    //  - CAN VIEW:
    //      - PATIENT INFO;
    //      - PATIENT DIAGNOSTICS;
    //      - PATIENT TREATMENTS;
    //  - CANNOT VEW:
    //      - CONSULTS (PATIENT INTERACTIONS WITH OTHER INSTITUTIONS OR DOCTORS);
    //      - NHS DETAILS ABOUT INSTITUTIONS, DOCTORS AND NURSES;
    //      - NHS ADMIN DETAILS;
    // HAS A MEDICAL LICENSE NUMBER.

    NURSE
    // CANNOT VIEW/EDIT MEDICOM USERS, EXCEPT THEIR OWN.
    // CANNOT VIEW/EDIT MEDICOM INSTITUTIONS, EXCEPT VIEWING THEIR OWN.
    // CAN ONLY EDIT THEIR OWN INSTITUTION'S MEDICOM CALENDAR.
    // CAN ACCESS NHS DATABASE:
    //  - CAN VIEW:
    //      - THEIR OWN INSTITUTION'S PATIENT INFO;
    //      - THEIR OWN INSTITUTION'S PATIENT DIAGNOSTICS;
    //      - THEIR OWN INSTITUTION'S PATIENT TREATMENTS;
    //  - CANNOT VEW:
    //      - CONSULTS (PATIENT INTERACTIONS WITH OTHER INSTITUTIONS OR DOCTORS);
    //      - NHS DETAILS ABOUT INSTITUTIONS, DOCTORS AND NURSES;
    //      - NHS ADMIN DETAILS;
    // HAS A NURSING LICENSE NUMBER.

}
